name: "Build to GIT"
description: ""
inputs:
  source:
    description: "Previously built folder (needs to be a repo)"
    required: false
    default: 'source'
  target:
    description: "Newly built code (doesn't need to be a repo)"
    required: false
    default: 'target'
outputs:
  manifest:
    description: "Manifest of files changed"
    value: ${{ steps.main.outputs.manifest }}
  manifest-raw:
    description: "GIT Diff of commited file"
    value: ${{ steps.main.outputs.manifest-raw }}
    
runs:
  using: "composite"
  steps:
    - name: Path Setup
      id: main
      shell: bash
      env:
        SOURCE_DIR: ${{ inputs.source }}
        TARGET_DIR: ${{ inputs.target }}
      run: "${{ github.action_path }}/main.sh"
