name: "Build to GIT"
description: ""
inputs:
  source:
    description: "Previously built folder (needs to be a repo)"
    required: false
    default: 'source'
  target:
    description: "Newly built code (doesn't need to be a repo)"
    required: false
    default: 'target'
  defer-push:
    description: "Do not push immediately"
    required: false
    default: "false"
  do-push:
    description: "Do a previously deferred push"
    required: false
    default: "false"
  force-ignore:
    description: "Force ignore files"
    required: false
    default: |
      /vendor/*
      !/vendor/composer
      /vendor/composer/*
      !/vendor/composer/installers
      !/vendor/composer/installed.json
outputs:
  manifest:
    description: "Manifest of files changed"
    value: ${{ steps.main.outputs.manifest }}
  manifest-raw:
    description: "GIT Diff of commited file"
    value: ${{ steps.main.outputs.manifest-raw }}
    
runs:
  using: "composite"
  steps:
    - name: Path Setup
      if: ${{ inputs.do-push == 'true' }}
      id: do-push
      shell: bash
      env:
        SOURCE_DIR: ${{ inputs.source }}
      run: "${{ github.action_path }}/do-push.sh"
    - name: Path Setup
      if: ${{ inputs.do-push != 'true' }}
      id: main
      shell: bash
      env:
        SOURCE_DIR: ${{ inputs.source }}
        TARGET_DIR: ${{ inputs.target }}
        DEFER_PUSH: ${{ inputs.defer-push }}
        FORCE_IGNORE: ${{ inputs.force-ignore }}
      run: "${{ github.action_path }}/main.sh"
